Documentation:
   Enabled: false
LineLength:
   Max: 99
Style/FrozenStringLiteralComment:
   Enabled: false
Style/BlockComments:
   Enabled: false
Style/ExpandPathArguments:
   Enabled: false
Metrics/BlockLength:
   Enabled: false